project:
  title: AIRODS HTTP-API EPOS-ORFEUS_CC-EOSC
  description: expose some endpoint for Epos ecosystem
  version: 1.0.6
  rapydo: 0.6.5
  extends: b2stage
  extends-from: submodules/b2stage

variables:
  submodules:
    b2stage:
      branch: 1.0.6
      online_url: https://github.com/EUDAT-B2STAGE/http-api.git
      path: b2stage
      if: true

  env:
    ACTIVATE_ICAT: 0
    ACTIVATE_MONGODB: 1
    IRODS_ANONYMOUS: 0
    IRODS_GUEST_USER: guest              # intended to work only with GSI
    IRODS_DEFAULT_ADMIN_USER: rodsminer  # intended to work only with GSI
    IRODS_DN:           # automatically computed within the docker network
    IRODS_AUTHSCHEME: credentials
    # IRODS_AUTHSCHEME: GSI
    ALCHEMY_API_DB: SQL_API
    
    # AIRODS
    AIRODS_STAGE_PATH_1: /BINGV/home/rods#INGV/areastage/

tags:
  #Swagger tags
